# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('nationality', models.DateField()),
                ('bio', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('url', models.URLField(max_length=255, verbose_name='Extenal Link URL')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('isbn', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('url', models.URLField(max_length=255, verbose_name='Extenal Link URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Author')),
            ],
        ),
    ]
