# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160426_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/catalogue/book'),
        ),
    ]
