# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/catalogue/homepage')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Extenal Link URL')),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Carousel Slide',
            },
        ),
    ]
