# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
