# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_mailinglistsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
